/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.idesi.proyecto.personal;

import com.idesi.proyecto.VentanaPrincipal;
import com.idesi.proyecto.recursos.Producto;

/**
 *
 * @author Hola
 */
public class VentanaPersonal extends javax.swing.JFrame {

    private VentanaPrincipal vtnPrincipal = null;
    private VentanaAgregar vtnAgregar = null;
    private VentanaReporte vtnReporte = null;
    private VentanaBuscar vtnBuscar = null;
    private VentanaModificar vtnModificar = null;
    private VentanaEliminar vtnEliminar = null;
    private VentanaAgregarProducto vtnAgregarProd = null;
    private Empleado[] empleados = new Empleado[5];
    private Producto[] productos;
    private int posEmp = 0;
    private int posProd = 0;
    private int posCitas = 0;

    /**
     * Creates new form VentanaPersonal
     */
    public VentanaPersonal() {
        initComponents();
    }

    public VentanaPersonal(VentanaPrincipal vtnPrincipal) {
        this.vtnPrincipal = vtnPrincipal;
        initComponents();
    }

    public void aplicarCambiosPersonal(int posEmp) {
        this.posEmp = posEmp;
        txtNoEmpleados.setText(String.valueOf(this.posEmp));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregarEmpleado = new javax.swing.JButton();
        btn_Reporte = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_agregarProducto = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblNoEmpleados = new javax.swing.JLabel();
        txtNoEmpleados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_agregarEmpleado.setText("Agregar un empleado");
        btn_agregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarEmpleadoActionPerformed(evt);
            }
        });

        btn_Reporte.setText("Reporte de empleados");
        btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteActionPerformed(evt);
            }
        });

        btn_Buscar.setText("Buscar un empleado");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        btn_Modificar.setText("Modificar Datos de un empleado");
        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar un empleado");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_agregarProducto.setText("Agregar un producto");
        btn_agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarProductoActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar a la ventana principal");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblNoEmpleados.setText("No. Empleados registrados:");

        txtNoEmpleados.setEditable(false);
        txtNoEmpleados.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_agregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblNoEmpleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(btnRegresar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarEmpleado)
                    .addComponent(lblNoEmpleados)
                    .addComponent(txtNoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Reporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Buscar)
                .addGap(7, 7, 7)
                .addComponent(btn_Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarProducto)
                    .addComponent(btnRegresar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        if (vtnModificar == null) {
            vtnModificar = new VentanaModificar(this, empleados);
        }

        vtnModificar.posEmp = this.posEmp;
        vtnModificar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ModificarActionPerformed

    private void btn_agregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarEmpleadoActionPerformed
        if (vtnAgregar == null) {
            vtnAgregar = new VentanaAgregar(this, empleados);
        }

        vtnAgregar.posEmp = this.posEmp;
        vtnAgregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_agregarEmpleadoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        vtnPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        if (vtnBuscar == null) {
            vtnBuscar = new VentanaBuscar(this, empleados);
        }

        vtnBuscar.posEmp = this.posEmp;
        vtnBuscar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        if (vtnEliminar == null) {
            vtnEliminar = new VentanaEliminar(this, empleados);
        }

        vtnEliminar.posEmp = this.posEmp;
        vtnEliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteActionPerformed
        if (vtnReporte == null) {
            vtnReporte = new VentanaReporte(this, empleados);
        }

        vtnReporte.posEmp = this.posEmp;
        vtnReporte.posCitas = this.posCitas;
        vtnReporte.actual = 0;
        vtnReporte.cargarDatos(0);        
        vtnReporte.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ReporteActionPerformed

    private void btn_agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarProductoActionPerformed
        if (vtnAgregarProd == null) {
            vtnAgregarProd = new VentanaAgregarProducto(this, empleados, productos);
        }

        vtnAgregarProd.posEmp = this.posEmp;
        vtnAgregarProd.posProd = this.posProd;       
        vtnAgregarProd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_agregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_Reporte;
    private javax.swing.JButton btn_agregarEmpleado;
    private javax.swing.JButton btn_agregarProducto;
    private javax.swing.JLabel lblNoEmpleados;
    private javax.swing.JTextField txtNoEmpleados;
    // End of variables declaration//GEN-END:variables
}
