package com.idesi.proyecto.clientes;

import com.idesi.proyecto.VentanaPrincipal;
import javax.swing.table.TableModel;
import com.idesi.proyecto.recursos.ImagenFondo;

/**
 *
 * @author Cristofer
 */
public class VentanaClientes extends javax.swing.JFrame {

    private VentanaPrincipal vtnPrincipal = null;
    private VentanaAgregar vtnAgregar = null;
    private VentanaBuscar vtnBuscar = null;
    private VentanaModificar vtnModificar = null;
    private VentanaEliminar vtnEliminar = null;
    private VentanaEstablecerCita vtnEstCita = null;
    private VentanaListaDeCitas vtnLisCita = null;
    ImagenFondo ejemplo = new ImagenFondo();
    private Cliente[] clientes = new Cliente[5];
    private Cita[] citas = new Cita[5];
    private int posClientes = 0;
    private int posCitas = 0;

    /**
     * Creates new form VentanaClientes
     */
    public VentanaClientes() {     
        initComponents();
    }

    public VentanaClientes(VentanaPrincipal vtnPrincipal) {
        this.vtnPrincipal = vtnPrincipal;
        this.setContentPane(ejemplo);
        initComponents();
    }

    public void aplicarCambiosCitas(int posCitas) {
        this.posCitas = posCitas;
        this.btnListaCitas.setEnabled(true);
    }

    public void aplicarCambiosClientes(int posClientes) {
        this.posClientes = posClientes;
        txtClientesRegistrados.setText(String.valueOf(this.posClientes));
        actualizarTabla();
        if(this.posClientes < 1){
            btnBuscar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            mni_Buscar_cliente.setEnabled(false);
            mni_Modificar_datos_de_un_cliente.setEnabled(false);
            mni_Eliminar_un_cliente.setEnabled(false);
        }else{
            btnBuscar.setEnabled(true);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
            mni_Buscar_cliente.setEnabled(true);
            mni_Modificar_datos_de_un_cliente.setEnabled(true);
            mni_Eliminar_un_cliente.setEnabled(true);
        }
    }

    public void aplicarCambiosClientes() {
        actualizarTabla();
    }

    private void actualizarTabla() {
        TableModel modelo = tblClientes.getModel();

        for (int i = 0; i < 5; i++) {
            modelo.setValueAt(null, i, 0);
            modelo.setValueAt(null, i, 1);
            modelo.setValueAt(null, i, 2);
            modelo.setValueAt(null, i, 3);
        }

        for (int x = 0; x < posClientes; x++) {
            modelo.setValueAt(clientes[x].getCódigo_de_cliente(), x, 0);
            modelo.setValueAt(clientes[x].getNombre(), x, 1);
            modelo.setValueAt(clientes[x].getEdad(), x, 2);
            modelo.setValueAt(clientes[x].getDomicilio(), x, 3);
        }

    }

    private void procesoRegresar() {
        vtnPrincipal.ajustarCambiosCitas(posCitas);
        vtnPrincipal.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCrearCita = new javax.swing.JButton();
        btnListaCitas = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblClientesRegistrados = new javax.swing.JLabel();
        txtClientesRegistrados = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mni_Agregar_Cliente = new javax.swing.JMenuItem();
        mni_Buscar_cliente = new javax.swing.JMenuItem();
        mni_Modificar_datos_de_un_cliente = new javax.swing.JMenuItem();
        mni_Eliminar_un_cliente = new javax.swing.JMenuItem();
        mni_Establecer_una_cita = new javax.swing.JMenuItem();
        mni_Lista_de_citas = new javax.swing.JMenuItem();
        mni_Regresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(527, 247));

        btnAgregar.setText("Agregar un cliente");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar cliente");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar datos de un cliente");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar un cliente");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCrearCita.setText("Establecer una cita");
        btnCrearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCitaActionPerformed(evt);
            }
        });

        btnListaCitas.setText("Lista de citas");
        btnListaCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaCitasActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblClientesRegistrados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientesRegistrados.setText("No. Clientes registrados: ");

        txtClientesRegistrados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtClientesRegistrados.setText("0");
        txtClientesRegistrados.setEnabled(false);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Edad", "Domicilio"
            }
        ));
        tblClientes.setDefaultEditor(Object.class,null);
        tblClientes.setRowHeight(tblClientes.getRowHeight() + 15);
        tblClientes.setPreferredSize(null);
        jScrollPane1.setViewportView(tblClientes);

        jMenu1.setText("Archivo");

        mni_Agregar_Cliente.setText("Agregar Cliente");
        mni_Agregar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Agregar_ClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mni_Agregar_Cliente);

        mni_Buscar_cliente.setText("Buscar cliente");
        mni_Buscar_cliente.setEnabled(false);
        mni_Buscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Buscar_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(mni_Buscar_cliente);

        mni_Modificar_datos_de_un_cliente.setText("Modificar datos de un cliente");
        mni_Modificar_datos_de_un_cliente.setEnabled(false);
        mni_Modificar_datos_de_un_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Modificar_datos_de_un_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(mni_Modificar_datos_de_un_cliente);

        mni_Eliminar_un_cliente.setText("Eliminar un cliente");
        mni_Eliminar_un_cliente.setEnabled(false);
        mni_Eliminar_un_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Eliminar_un_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(mni_Eliminar_un_cliente);

        mni_Establecer_una_cita.setText("Establecer una cita");
        mni_Establecer_una_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Establecer_una_citaActionPerformed(evt);
            }
        });
        jMenu1.add(mni_Establecer_una_cita);

        mni_Lista_de_citas.setText("Lista de citas");
        mni_Lista_de_citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Lista_de_citasActionPerformed(evt);
            }
        });
        jMenu1.add(mni_Lista_de_citas);

        mni_Regresar.setText("Regresar");
        mni_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_RegresarActionPerformed(evt);
            }
        });
        jMenu1.add(mni_Regresar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListaCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClientesRegistrados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClientesRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(lblClientesRegistrados)
                    .addComponent(txtClientesRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrearCita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListaCitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (vtnAgregar == null) {
            vtnAgregar = new VentanaAgregar(this, clientes);
        }

        vtnAgregar.posClientes = this.posClientes;
        vtnAgregar.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (vtnBuscar == null) {
            vtnBuscar = new VentanaBuscar(this, clientes);
        }

        vtnBuscar.posClientes = this.posClientes;
        vtnBuscar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (vtnModificar == null) {
            vtnModificar = new VentanaModificar(this, clientes);
        }

        vtnModificar.posClientes = this.posClientes;
        vtnModificar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (vtnEliminar == null) {
            vtnEliminar = new VentanaEliminar(this, clientes);
        }

        vtnEliminar.posClientes = this.posClientes;
        vtnEliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCitaActionPerformed
        if (vtnEstCita == null) {
            vtnEstCita = new VentanaEstablecerCita(this, citas);
        }

        vtnEstCita.posCitas = this.posCitas;
        vtnEstCita.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearCitaActionPerformed

    private void btnListaCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaCitasActionPerformed
        if (vtnLisCita == null) {
            vtnLisCita = new VentanaListaDeCitas(this, citas);
        }

        vtnLisCita.aplicarCambios(this.posCitas);
        vtnLisCita.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListaCitasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        procesoRegresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void mni_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_RegresarActionPerformed
        this.btnRegresarActionPerformed(evt);
    }//GEN-LAST:event_mni_RegresarActionPerformed

    private void mni_Agregar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Agregar_ClienteActionPerformed
        this.btnAgregarActionPerformed(evt);
    }//GEN-LAST:event_mni_Agregar_ClienteActionPerformed

    private void mni_Buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Buscar_clienteActionPerformed
        this.btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_mni_Buscar_clienteActionPerformed

    private void mni_Modificar_datos_de_un_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Modificar_datos_de_un_clienteActionPerformed
        this.btnModificarActionPerformed(evt);
    }//GEN-LAST:event_mni_Modificar_datos_de_un_clienteActionPerformed

    private void mni_Eliminar_un_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Eliminar_un_clienteActionPerformed
        this.btnEliminarActionPerformed(evt);
    }//GEN-LAST:event_mni_Eliminar_un_clienteActionPerformed

    private void mni_Establecer_una_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Establecer_una_citaActionPerformed
        this.btnCrearCitaActionPerformed(evt);
    }//GEN-LAST:event_mni_Establecer_una_citaActionPerformed

    private void mni_Lista_de_citasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Lista_de_citasActionPerformed
        this.btnListaCitasActionPerformed(evt);
    }//GEN-LAST:event_mni_Lista_de_citasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearCita;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListaCitas;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClientesRegistrados;
    private javax.swing.JMenuItem mni_Agregar_Cliente;
    private javax.swing.JMenuItem mni_Buscar_cliente;
    private javax.swing.JMenuItem mni_Eliminar_un_cliente;
    private javax.swing.JMenuItem mni_Establecer_una_cita;
    private javax.swing.JMenuItem mni_Lista_de_citas;
    private javax.swing.JMenuItem mni_Modificar_datos_de_un_cliente;
    private javax.swing.JMenuItem mni_Regresar;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtClientesRegistrados;
    // End of variables declaration//GEN-END:variables
}
