/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.idesi.proyecto;

import com.idesi.proyecto.clientes.VentanaClientes;
import com.idesi.proyecto.personal.VentanaPersonal;
import com.idesi.proyecto.recursos.Producto;
import com.idesi.proyecto.recursos.VentanaRecursos;
import com.idesi.proyecto.recursos.ImagenFondo;
/**-
 *
 * @author Cristofer
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private VentanaPersonal vtnPersonal = null;
    private VentanaClientes vtnClientes = null;
    private VentanaRecursos vtnRecursos = null;
    
    private Producto[] productos = new Producto[5];
    ImagenFondo ejemplo = new ImagenFondo();
    private int posProducto = 0;
    private int posCitas = 0;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.setContentPane(ejemplo);
        initComponents();
    }
    
    public void ajustarCambiosCitas(int posCitas){
        this.posCitas = posCitas;
    }
    
    public void ajustarCambiosProductos(int posProducto){
        this.posProducto = posProducto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Control = new javax.swing.JButton();
        btn_Recursos = new javax.swing.JButton();
        btn_Clientes = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_Manejo_de_Clientes = new javax.swing.JMenu();
        mn_Recursos_Materiales = new javax.swing.JMenuItem();
        mn_Control_de_personal = new javax.swing.JMenuItem();
        mn_Manejo_de_clientes = new javax.swing.JMenuItem();
        mn_Salir_del_Sistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn_Control.setText("Control de Personal");
        btn_Control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ControlActionPerformed(evt);
            }
        });

        btn_Recursos.setText("Recursos Materiales");
        btn_Recursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecursosActionPerformed(evt);
            }
        });

        btn_Clientes.setText("Manejo de Clientes");
        btn_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClientesActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir del Sistema");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/idesi/proyecto/Medicamento.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/idesi/proyecto/Personal.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/idesi/proyecto/Clientejpg.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/idesi/proyecto/Salir_del_sistema.jpg"))); // NOI18N

        mn_Manejo_de_Clientes.setText("Archivo");

        mn_Recursos_Materiales.setText("Recursos Materiales");
        mn_Recursos_Materiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Recursos_MaterialesActionPerformed(evt);
            }
        });
        mn_Manejo_de_Clientes.add(mn_Recursos_Materiales);

        mn_Control_de_personal.setText("Control de personal");
        mn_Control_de_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Control_de_personalActionPerformed(evt);
            }
        });
        mn_Manejo_de_Clientes.add(mn_Control_de_personal);

        mn_Manejo_de_clientes.setText("Manejo de Clientes");
        mn_Manejo_de_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Manejo_de_clientesActionPerformed(evt);
            }
        });
        mn_Manejo_de_Clientes.add(mn_Manejo_de_clientes);

        mn_Salir_del_Sistema.setText("Salir del Sistema");
        mn_Salir_del_Sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_Salir_del_SistemaActionPerformed(evt);
            }
        });
        mn_Manejo_de_Clientes.add(mn_Salir_del_Sistema);

        jMenuBar1.add(mn_Manejo_de_Clientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(btn_Recursos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btn_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Control, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Recursos)
                    .addComponent(btn_Control))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Clientes)
                    .addComponent(btn_Salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecursosActionPerformed
         if(vtnRecursos == null){
            vtnRecursos = new VentanaRecursos(this, productos);
        }
        
        vtnRecursos.Tamaño = this.posProducto;
        vtnRecursos.Enable_Faltantes();
        vtnRecursos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RecursosActionPerformed

    private void btn_ControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ControlActionPerformed
        if(vtnPersonal == null){
            vtnPersonal = new VentanaPersonal(this, productos);
        }
        
        vtnPersonal.aplicarCambiosExternos(this.posProducto, this.posCitas);
        vtnPersonal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ControlActionPerformed

    private void btn_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClientesActionPerformed
        if(vtnClientes == null){
            vtnClientes = new VentanaClientes(this);
        }
        
        vtnClientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ClientesActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void mn_Recursos_MaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Recursos_MaterialesActionPerformed
        this.btn_RecursosActionPerformed(evt);
    }//GEN-LAST:event_mn_Recursos_MaterialesActionPerformed

    private void mn_Control_de_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Control_de_personalActionPerformed
        this.btn_ControlActionPerformed(evt);
    }//GEN-LAST:event_mn_Control_de_personalActionPerformed

    private void mn_Manejo_de_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Manejo_de_clientesActionPerformed
        this.btn_ClientesActionPerformed(evt);   
    }//GEN-LAST:event_mn_Manejo_de_clientesActionPerformed

    private void mn_Salir_del_SistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_Salir_del_SistemaActionPerformed
        this.btn_SalirActionPerformed(evt);
    }//GEN-LAST:event_mn_Salir_del_SistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clientes;
    private javax.swing.JButton btn_Control;
    private javax.swing.JButton btn_Recursos;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mn_Control_de_personal;
    private javax.swing.JMenu mn_Manejo_de_Clientes;
    private javax.swing.JMenuItem mn_Manejo_de_clientes;
    private javax.swing.JMenuItem mn_Recursos_Materiales;
    private javax.swing.JMenuItem mn_Salir_del_Sistema;
    // End of variables declaration//GEN-END:variables
}
